services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_POSTGRES_DB:-library}
    ports:
      - "${DB_POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
